### ISSUE TITLE
About code debugging

### ISSUE THREAD

**Issue by soberguo** [Koorye/DePT#5]
How can I debug your code? Although I set a breakpoint in the model under trainers, it does not execute here. I don’t understand how your code is running.

**Comment by Koorye** [comment]
Thank you for your attention to this repo!  This repo can be debugged normally: 

![image](https://github.com/user-attachments/assets/f7ae50cd-0b7f-44eb-8d3c-ad57558a4320)

Failure to debug may be due to the following reasons: 
1. You need to run debug from `train.py` instead of `parallel_runner.py`, which calls `parallel_runner.py` using `os.system` and create multi-threading running programs, may not be caught by the debugger.
2. Some codes are only called during inference and will not be run during training.

Hope the above suggestions can help you!
